/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataMahasiswa;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author radmv
 */
public class DataNilai extends javax.swing.JFrame {

    /**
     * Creates new form DataNilai
     */
    public DataNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
    String koneksi = "jdbc:mysql://localhost/db_akademik";
    String user = "root";
    String pass = "";
    Connection connection;
    Statement statement;
    
    private void loaddata(){
        try {
            cbonim.removeAllItems();
        String sql = "SELECT * FROM mahasiswa";
        ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                cbonim.addItem(rs.getString("nim"));
            }
            rs.close();
            loadnama();
        } catch (Exception e) {
            System.err.println("Terjadi Kesalahan");
        }
        
    }
    
    private void loadnama(){
        try {
        String sql = "SELECT * FROM mahasiswa WHERE nim = '" + cbonim.getSelectedItem() + "'";
        ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                txtnama.setText(rs.getString("nama"));
            }
            rs.close();
        } catch (Exception e) {
            System.err.println("Terjadi Kesalahan -n");
        }
        
    }
    
    private void bersih(){
        txtmakul.setText("");
        cbonilai.setSelectedItem(0);
        try {
            String sql = "SELECT mahasiswa.nim, mahasiswa.nama, nilaimakul.makul, nilaimakul.nilai "
                    + "FROM mahasiswa, nilaimakul WHERE mahasiswa.nim = nilaimakul.nim";
            ResultSet rs = statement.executeQuery(sql);
            final String[] header = {"NIM", "NAMA", "MAKUL", "NILAI"};
            rs.last();
            
            int n = rs.getRow();
            
            Object[][] data = new Object[n][4];
            int p = 0;
            rs.beforeFirst();
            while (rs.next()) {
                data [p][0] = rs.getString(1);
                data [p][1] = rs.getString(2);
                data [p][2] = rs.getString(3);
                data [p][3] = rs.getString(4);
                p++;
            }
            tabdata.setModel(new javax.swing.table.DefaultTableModel(data, header));
            tabdata.setAlignmentX(CENTER_ALIGNMENT);
        } catch (Exception DBException) {
            System.err.println("Error=" + DBException);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbonim = new javax.swing.JComboBox<>();
        cbonilai = new javax.swing.JComboBox<>();
        txtnama = new javax.swing.JTextField();
        txtmakul = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnreload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabdata = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setText("DATA NILAI MATA KULIAH");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel4.setText("MAKUL");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel5.setText("NILAI");

        cbonim.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        cbonim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbonim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbonimItemStateChanged(evt);
            }
        });
        cbonim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbonimMouseClicked(evt);
            }
        });
        cbonim.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cbonimInputMethodTextChanged(evt);
            }
        });

        cbonilai.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        cbonilai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));

        txtnama.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtnama.setEnabled(false);
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtmakul.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtmakul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmakulActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnreload.setFont(new java.awt.Font("Poppins", 0, 8)); // NOI18N
        btnreload.setText("reload");
        btnreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmakul)
                            .addComponent(cbonilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbonim, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnreload))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbonim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreload))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmakul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbonilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btncancel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tabdata.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tabdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabdata);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel6.setText("SEARCH");

        txtcari.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            int reply = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM nilaimakul WHERE nim = '" + cbonim.getSelectedItem() + "'";
                       sql += "&& makul = '" + tabdata.getValueAt(tabdata.getSelectedRow(), 2).toString() + "'";
                statement.executeUpdate(sql);
            }
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Hapus data gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error=" + DBException);
        }
        bersih();
        loaddata();
        btnsave.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtmakulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmakulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmakulActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = "jdbc:mysql://localhost/db_akademik";
            connection = (Connection) DriverManager.getConnection(koneksi, user, pass);
            statement = (Statement) connection.createStatement();
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "koneksi gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:" + DBException);
        }
        bersih();
        loaddata();
//        loadnama();
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
        txtmakul.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            String sql;
            {
                sql = "INSERT INTO nilaimakul VALUES ('";
                sql += cbonim.getSelectedItem() + "','";
                sql += txtmakul.getText() + "','";
                sql += cbonilai.getSelectedItem() + "')";
            }
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Simpan data berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Simpan data gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error=" + DBException);
        }
        bersih();
        loaddata();
        cbonim.requestFocus();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void tabdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabdataMouseClicked
        cbonim.setSelectedItem(tabdata.getValueAt(tabdata.getSelectedRow(), 0).toString());
        txtnama.setText(tabdata.getValueAt(tabdata.getSelectedRow(), 1).toString());
        txtmakul.setText(tabdata.getValueAt(tabdata.getSelectedRow(), 2).toString());
        cbonilai.setSelectedItem(tabdata.getValueAt(tabdata.getSelectedRow(), 3).toString());
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);
        cbonim.setEditable(false);
        btnsave.setEnabled(false);
        btnreload.setEnabled(false);
    }//GEN-LAST:event_tabdataMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            String sql;
            {
                sql = "UPDATE nilaimakul SET makul = '";
                sql += txtmakul.getText() + "', nilai = '";
                sql += cbonilai.getSelectedItem() + "'";
                sql += "WHERE nim = '" + cbonim.getSelectedItem() + "'";
                sql += "&& makul = '" + tabdata.getValueAt(tabdata.getSelectedRow(), 2).toString() + "'";
            }
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Update data berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Update data gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error=" + DBException);
        }
        bersih();
        loaddata();
        btnsave.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void cbonimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbonimItemStateChanged
        
//        loadnama();
    }//GEN-LAST:event_cbonimItemStateChanged

    private void cbonimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbonimMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbonimMouseClicked

    private void cbonimInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbonimInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbonimInputMethodTextChanged

    private void btnreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreloadActionPerformed
        loadnama();
    }//GEN-LAST:event_btnreloadActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
       DefaultTableModel tabel = new DefaultTableModel();
       tabel.addColumn("NIM");
       tabel.addColumn("NAMA");
       tabel.addColumn("MAKUL");
       tabel.addColumn("NILAI"); 
       
        try {
            String sql = "SELECT nilaimakul.nim, mahasiswa.nama, nilaimakul.makul, nilaimakul.nilai FROM mahasiswa, nilaimakul WHERE nilaimakul.nim like '%" + txtcari.getText() + "%'";
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
            });
                tabdata.setModel(tabel);
            }
        } catch (Exception DBException) {
            System.err.println("Error=" + DBException);
        }
    }//GEN-LAST:event_txtcariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreload;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbonilai;
    private javax.swing.JComboBox<String> cbonim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabdata;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtmakul;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
